Description: >
  Cloudfront distribution for Capstone.

Parameters:
  LBAddr:
    Description: Load Balancer address.
    Type: String

Resources:
  
  CloudFrontOriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Origin Access Identity for Serverless Static Website

  WebpageCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub "${LBAddr}"
            Id: webpage
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        Enabled: True
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: False
          TargetOriginId: webpage
          ViewerProtocolPolicy: redirect-to-https

Outputs:
  LBAddr:
    Value: !Sub ${LBAddr}
    Description: Load Balancer URL
    Export:
      Name: LBAddr
