- name: Copy dist to EC2 server
  hosts: my_ec2_server
  become: yes
  tasks:
    - name: Copy files to remote server
      copy:
        src: ~/project/docker/
        dest: /home/ubuntu/

- name: hadolint Dockerfile
  hosts: my_ec2_server
  become: yes
  tasks:
    - name: Run hadolint on Dockerfile
      command: hadolint --ignore DL3042 /home/ubuntu/Dockerfile
      register: output

- name: Start Docker container
  hosts: localhost
  tasks:
    - name: Start Docker container
      docker_container:
        name: my_container
        image: python:3.7.3-stretch
        ports:
          - "80:80"
        volumes:
          - /app:/app
        command: python app.py
