---
- name: "Copy dist to EC2 server"
  become: yes
  copy:
    src: ~/project/docker/
    dest: /home/ubuntu/

- name: "hadolint Dockerfile"
  command: hadolint --ignore DL3042 /home/ubuntu/Dockerfile
  register: output

