---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install docker"
  become: yes
  apt:
    name: docker
    state: present

- name: "install pylint"
  become: yes
  apt:
    name: pylint
    state: present

- name: "Install Hadolint"
  become: true
  apt:
    name: curl
    state: present

- name: "Download Hadolint binary"
  become: true
  shell: "curl -L 'https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64' -o /usr/local/bin/hadolint"
  args:
    creates: /usr/local/bin/hadolint
    executable: /bin/bash

- name: "Make Hadolint binary executable"
  become: true
  file:
    path: /usr/local/bin/hadolint
    mode: "+x"

- name: "install make"
  apt:
    name: make
    state: present

- name: Install minikube
  become: yes

  vars:
    minikube_version: latest
    minikube_url: https://storage.googleapis.com/minikube/releases/{{ minikube_version }}/minikube-linux-amd64
    minikube_bin_path: /usr/local/bin/minikube

    tasks:
      - name: Download minikube binary
        shell: "curl -L '{{ minikube_url }}' -o '{{ minikube_bin_path }}'"
        args:
          creates: "{{ minikube_bin_path }}"
          executable: /bin/bash

      - name: Make minikube binary executable
        file:
          path: "{{ minikube_bin_path }}"
          mode: "+x"

      - name: Check minikube version and status
        shell: |
          {{ minikube_bin_path }} version
          {{ minikube_bin_path }} status
